export const featuredListings = [
  {
    crop: "Cocoa Beans",
    quantity: "2,000 kg available",
    location: "Kumba, South West",
    price: "XAF 1,650 / kg",
    status: "verified",
    imageClass: "bg-[linear-gradient(135deg,#5B3A1D,#C08A46)]",
  },
  {
    crop: "Arabica Coffee",
    quantity: "800 kg available",
    location: "Bafoussam, West",
    price: "XAF 2,100 / kg",
    status: "export-ready",
    imageClass: "bg-[linear-gradient(135deg,#3F5F3B,#B79A64)]",
  },
  {
    crop: "White Maize",
    quantity: "5,000 kg available",
    location: "Garoua, North",
    price: "XAF 420 / kg",
    status: "negotiable",
    imageClass: "bg-[linear-gradient(135deg,#E6C96F,#F7EDD5)]",
  },
  {
    crop: "Penja Pepper",
    quantity: "300 kg available",
    location: "Penja, Littoral",
    price: "XAF 8,750 / kg",
    status: "export-ready",
    imageClass: "bg-[linear-gradient(135deg,#2E2E2E,#9A7445)]",
  },
  {
    crop: "Plantain",
    quantity: "1,200 bunches available",
    location: "Ebolowa, South",
    price: "XAF 3,200 / bunch",
    status: "verified",
    imageClass: "bg-[linear-gradient(135deg,#4E7D2E,#D4B74A)]",
  },
  {
    crop: "Palm Oil",
    quantity: "500 litres available",
    location: "Eseka, Centre",
    price: "XAF 1,900 / L",
    status: "pending",
    imageClass: "bg-[linear-gradient(135deg,#6B3E1F,#D8903C)]",
  },
  {
    crop: "Cassava Flour",
    quantity: "1,500 kg available",
    location: "Bamenda, North West",
    price: "XAF 560 / kg",
    status: "negotiable",
    imageClass: "bg-[linear-gradient(135deg,#E6D8B2,#F9F1DD)]",
  },
  {
    crop: "Export Banana",
    quantity: "10 tonnes available",
    location: "Mundemba, South West",
    price: "XAF 390 / kg",
    status: "export-ready",
    imageClass: "bg-[linear-gradient(135deg,#7AA645,#E6C95A)]",
  },
];

export const featuredFarmers = [
  {
    initials: "JN",
    name: "Jean Ngum",
    location: "Kumba, South West",
    crops: ["Cocoa", "Plantain"],
    badges: ["verified", "export-ready"],
    rating: "4.9",
    reviews: 42,
    stats: [
      { label: "Orders", value: "128" },
      { label: "On-time", value: "96%" },
    ],
  },
  {
    initials: "AK",
    name: "Amina Kofi",
    location: "Bafoussam, West",
    crops: ["Coffee", "Maize"],
    badges: ["verified", "negotiable"],
    rating: "4.8",
    reviews: 37,
    stats: [
      { label: "Orders", value: "94" },
      { label: "On-time", value: "93%" },
    ],
  },
  {
    initials: "PM",
    name: "Paul Meka",
    location: "Penja, Littoral",
    crops: ["Pepper", "Cassava"],
    badges: ["verified", "export-ready"],
    rating: "5.0",
    reviews: 18,
    stats: [
      { label: "Orders", value: "63" },
      { label: "On-time", value: "98%" },
    ],
  },
  {
    initials: "SN",
    name: "Sarah Ndzi",
    location: "Bamenda, North West",
    crops: ["Cassava", "Beans"],
    badges: ["verified", "pending"],
    rating: "4.7",
    reviews: 29,
    stats: [
      { label: "Orders", value: "71" },
      { label: "On-time", value: "91%" },
    ],
  },
];

export const regionHighlights = [
  {
    name: "South West",
    crops: ["Cocoa", "Banana", "Plantain"],
    emphasis: "Export clusters",
    summary: "High-volume crop corridors with active buyer demand and faster inspection coordination.",
    tradeSignal: "12 active clusters",
  },
  {
    name: "West",
    crops: ["Coffee", "Irish Potato", "Beans"],
    emphasis: "Highland growers",
    summary: "Reliable specialty and staple crop supply from cooperative-led production zones.",
    tradeSignal: "8 cooperative hubs",
  },
  {
    name: "Littoral",
    crops: ["Penja Pepper", "Palm Oil", "Cassava"],
    emphasis: "Port access",
    summary: "Trade-friendly routes for premium crops and quicker movement toward Douala logistics.",
    tradeSignal: "4 fast routes",
  },
  {
    name: "Centre",
    crops: ["Palm Oil", "Maize", "Groundnut"],
    emphasis: "Buyer logistics hub",
    summary: "Balanced supply and easier coordination for domestic buyers and regional distribution.",
    tradeSignal: "9 active warehouses",
  },
];
